"""initial schema

Revision ID: 1bf9e735f580
Revises: 
Create Date: 2026-04-16 21:37:13.102298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf9e735f580'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('competitor', 'market_source', name='companytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('internal_company_context',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('target_industries', sa.JSON(), nullable=True),
    sa.Column('target_segments', sa.JSON(), nullable=True),
    sa.Column('core_capabilities', sa.JSON(), nullable=True),
    sa.Column('strategic_priorities', sa.JSON(), nullable=True),
    sa.Column('differentiators', sa.JSON(), nullable=True),
    sa.Column('relevant_competitive_areas', sa.JSON(), nullable=True),
    sa.Column('non_focus_areas', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_digests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_signals', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Enum('news', 'blog', 'product', 'press', 'jobs', name='sourcetype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_raw_html', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_analysed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('signal_type', sa.Enum('product_update', 'ai_announcement', 'partnership', 'positioning_change', 'target_market_change', 'event_or_thought_leadership', 'hiring_signal', 'other', name='signaltype'), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('sources')
    op.drop_table('weekly_digests')
    op.drop_table('internal_company_context')
    op.drop_table('companies')
    # ### end Alembic commands ###
