"""add last_signal_relevance to discovered_pages

Revision ID: 3d201074a3d3
Revises: 72d3b0ef4607
Create Date: 2026-04-21 21:36:48.567027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d201074a3d3'
down_revision: Union[str, Sequence[str], None] = '72d3b0ef4607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crawl_briefings_crawl_run_id'), 'crawl_briefings', ['crawl_run_id'], unique=False)
    op.add_column('discovered_pages', sa.Column('last_signal_relevance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovered_pages', 'last_signal_relevance')
    op.drop_index(op.f('ix_crawl_briefings_crawl_run_id'), table_name='crawl_briefings')
    # ### end Alembic commands ###
