"""add source crawl_status content_hash last_changed_at

Revision ID: 6a4b042c5d51
Revises: 80ac42b11dc9
Create Date: 2026-04-19 16:52:21.790654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a4b042c5d51"
down_revision: Union[str, Sequence[str], None] = "80ac42b11dc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first for PostgreSQL
    crawl_status_enum = sa.Enum("new", "known", "changed", name="crawlstatus")
    crawl_status_enum.create(op.get_bind(), checkfirst=True)

    # Add columns
    op.add_column(
        "sources",
        sa.Column(
            "crawl_status", crawl_status_enum, server_default="new", nullable=False
        ),
    )
    op.add_column(
        "sources", sa.Column("content_hash", sa.String(length=64), nullable=True)
    )
    op.add_column("sources", sa.Column("last_changed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "last_changed_at")
    op.drop_column("sources", "content_hash")
    op.drop_column("sources", "crawl_status")

    # Drop enum type
    crawl_status_enum = sa.Enum("new", "known", "changed", name="crawlstatus")
    crawl_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
