"""add crawl briefings

Revision ID: 72d3b0ef4607
Revises: 8943143c913c
Create Date: 2026-04-21 20:11:06.204915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d3b0ef4607'
down_revision: Union[str, Sequence[str], None] = '8943143c913c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_briefings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crawl_run_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_briefings')
    # ### end Alembic commands ###
