"""add_websearch_tables

Revision ID: 80ac42b11dc9
Revises: 81bd3e2d0514
Create Date: 2026-04-19 14:59:48.375418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "80ac42b11dc9"
down_revision: Union[str, Sequence[str], None] = "81bd3e2d0514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_queries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("query_text", sa.String(length=500), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("search_intent", sa.String(length=100), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("found_via_query", sa.String(length=500), nullable=True),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column(
            "source_type_guess",
            postgresql.ENUM(
                "news",
                "blog",
                "product",
                "press",
                "jobs",
                name="sourcetype",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "approved",
                "rejected",
                "monitored",
                name="sourcecandidatestatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_candidates_domain"),
        "source_candidates",
        ["domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_candidates_url"), "source_candidates", ["url"], unique=False
    )
    op.create_table(
        "search_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("search_query_id", sa.String(length=36), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "done", "error", name="searchrunstatus"),
            nullable=False,
        ),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["search_queries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("search_run_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending", "fetched", "skipped", "error", name="searchresultstatus"
            ),
            nullable=False,
        ),
        sa.Column("linked_document_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["linked_document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["search_run_id"],
            ["search_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_results_url"), "search_results", ["url"], unique=False
    )
    op.add_column("documents", sa.Column("from_search", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "from_search")
    op.drop_index(op.f("ix_search_results_url"), table_name="search_results")
    op.drop_table("search_results")
    op.drop_table("search_runs")
    op.drop_index(op.f("ix_source_candidates_url"), table_name="source_candidates")
    op.drop_index(op.f("ix_source_candidates_domain"), table_name="source_candidates")
    op.drop_table("source_candidates")
    op.drop_table("search_queries")
    # Drop the enums we created (but NOT sourcetype - it's used elsewhere)
    sa.Enum(name="sourcecandidatestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="searchrunstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="searchresultstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
