"""add_discovered_pages

Revision ID: 81bd3e2d0514
Revises: 1bf9e735f580
Create Date: 2026-04-17 12:50:01.867002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bd3e2d0514'
down_revision: Union[str, Sequence[str], None] = '1bf9e735f580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'known', 'changed', 'ignored', name='discoveredpagestatus'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_discovered_pages_content_hash'), 'discovered_pages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_discovered_pages_source_id'), 'discovered_pages', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_pages_source_id'), table_name='discovered_pages')
    op.drop_index(op.f('ix_discovered_pages_content_hash'), table_name='discovered_pages')
    op.drop_table('discovered_pages')
    # ### end Alembic commands ###
