"""add crawl_runs and crawl_run_sources

Revision ID: 8943143c913c
Revises: 6a4b042c5d51
Create Date: 2026-04-19 22:05:10.095982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8943143c913c"
down_revision: Union[str, Sequence[str], None] = "6a4b042c5d51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running", "completed", "failed", "cancelled", name="crawlrunstatus"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("total_sources", sa.Integer(), nullable=True),
        sa.Column("total_new", sa.Integer(), nullable=True),
        sa.Column("total_skipped", sa.Integer(), nullable=True),
        sa.Column("total_errors", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_run_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("crawl_run_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "skipped",
                name="crawlrunsourcestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "current_step",
            sa.Enum(
                "fetching",
                "extracting",
                "analysing",
                "discovering",
                name="crawlrunstep",
            ),
            nullable=True,
        ),
        sa.Column("new_documents", sa.Integer(), nullable=True),
        sa.Column("skipped", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"],
            ["crawl_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_run_sources_crawl_run_id"),
        "crawl_run_sources",
        ["crawl_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_crawl_run_sources_crawl_run_id"), table_name="crawl_run_sources"
    )
    op.drop_table("crawl_run_sources")
    op.drop_table("crawl_runs")
    sa.Enum(name="crawlrunstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="crawlrunsourcestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="crawlrunstep").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
